### ISSUE TITLE
Word-o-mat disappears from Glyphs 2 menus with install of Glyphs 2.6.7

### ISSUE THREAD

**Issue by positype** [schriftgestalt/word-o-mat#8]
subsequent uninstalls and reinstalls have not remedied the issue

**Comment by schriftgestalt** [comment]
The latest cutting edge version should fix the issue.

**Comment by positype** [comment]
Well, oddly, after installing the new one, restarting my system, the plugin is still not appearing in my Edit menu.

Glyphs 2.6.7 installed
macOS 11.6.4

Can I try anything else?

**Comment by schriftgestalt** [comment]
you need Glyphs 2.6.8. Activate "Show cutting edge versions" in Preferences > Update.

**Comment by positype** [comment]
Thank you Georg. This system had cutting edge off, despite thinking it was on.

Works perfectly.
